Makefile

Fixes #
```release-note
NONE
```

chore(build): Update version to v0.1.4-alpha.4

---

Makefile
build/controller/Dockerfile
pkg/status/assistants/configmap.go
pkg/status/assistants/register.go
pkg/status/assistants/secret.go

Support detections of configmap and secret
Fixes #
/cc @zoumo 
```release-note
NONE
```

feat(status): support detections of configmap and secret

---

pkg/controller/status/controller.go
pkg/status/assistants/apps/v1/daemonset.go
pkg/status/assistants/apps/v1/deployment.go
pkg/status/assistants/apps/v1/register.go
pkg/status/assistants/apps/v1/statefulset.go
pkg/status/assistants/apps/v1beta1/deployment.go
pkg/status/assistants/apps/v1beta1/register.go
pkg/status/assistants/apps/v1beta1/statefulset.go
pkg/status/assistants/apps/v1beta2/daemonset.go
pkg/status/assistants/apps/v1beta2/deployment.go
pkg/status/assistants/apps/v1beta2/register.go
pkg/status/assistants/apps/v1beta2/statefulset.go
pkg/status/assistants/batch/v1/job.go
pkg/status/assistants/batch/v1/register.go
pkg/status/assistants/batch/v1beta1/cronjob.go
pkg/status/assistants/batch/v1beta1/register.go
pkg/status/assistants/batch/v2alpha1/cronjob.go
pkg/status/assistants/batch/v2alpha1/register.go
pkg/status/assistants/core/v1/configmap.go
pkg/status/assistants/core/v1/pvc.go
pkg/status/assistants/core/v1/register.go
pkg/status/assistants/core/v1/secret.go
pkg/status/assistants/core/v1/service.go
pkg/status/assistants/extensions/v1beta1/daemonset.go
pkg/status/assistants/extensions/v1beta1/deployment.go
pkg/status/assistants/extensions/v1beta1/register.go
pkg/status/assistants/register.go

Fixes #
/cc @refactor(stauts): support mutiple group versions for one kind
```release-note
refactor(stauts): support mutiple group versions for one kind
```

refactor(stauts): support mutiple group versions for one kind

---

Makefile
cmd/controller/app/controllers.go

Fixes #
```release-note
fix: stop gc controller because k8s already handle it
```

fix: stop gc controller because k8s already handle it

---

Makefile
cmd/controller/app/controllers.go
pkg/controller/release/controller.go
pkg/release/handler.go

Fixes #
```release-note
NONE
```

feat: resync release when subresources are deleted

---

Makefile
pkg/storage/release.go
pkg/storage/release_test.go

Fixes #
```release-note
NONE
```

fix: avoid patching conditions if there is no change

---

OWNERS

chore(OWNERS): add li-ang to owner
Fixes #
/cc @zoumo 
```release-note
NONE
```

chore(OWNERS): add li-ang to owner

---

Makefile.expansion
build/controller/Dockerfile

Fixes #
Reference to #
```release-note
NONE
```

fix(Makefile): fix Makefile golang build image

---

pkg/status/assistants/apps/v1/deployment.go

Fixes https://github.com/caicloud/quality/issues/417
Reference to #
/cc @zoumo  @kdada 
```release-note
NONE
```

fix(status): fix release status

---

pkg/status/assistants/apps/v1beta1/deployment.go
pkg/status/assistants/apps/v1beta2/deployment.go
pkg/status/assistants/extensions/v1beta1/deployment.go

https://github.com/caicloud/rudder/pull/41 这个值改掉了一部分，现在尽量都改掉，保持统一
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```

fix(status): fix release status for deployment application

---

pkg/kube/client.go

fix(job): fix update job
Fixes #
Reference to https://github.com/caicloud/quality/issues/1027
/cc @zoumo 
```release-note
NONE
```

fix(job): fix update job

---

Makefile.expansion
build/controller/Dockerfile

Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```

build: use alpine instead of debian

---

CODEOWNERS
OWNERS

chore(*): modify OWNERS & CODEOWNERS
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```

chore(*): modify OWNERS & CODEOWNERS

---

Gopkg.lock
pkg/controller/status/controller.go
vendor/github.com/caicloud/clientset/pkg/apis/release/v1alpha1/types.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/daemonset.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/deployment.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/longrunning.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/replicaset.go
vendor/github.com/caicloud/rudder-client/status/batch/v1/job.go
vendor/github.com/caicloud/rudder-client/status/batch/v1beta1/cronjob.go
vendor/github.com/caicloud/rudder-client/status/core/v1/pvc.go

Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```

feat(status): use progressing instead of processing

---

Makefile
pkg/kube/client.go

fix: add judgeOwnKind method for resource update
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```

 fix: add judgeOwnKind method for resource update

---

Gopkg.lock
pkg/controller/status/controller.go
pkg/release/handler.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/daemonset.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/longrunning.go

Fixes #
Reference to #
```release-note
NONE
```

fix: set reason and message only if the resource is failed

---

pkg/render/tree.go

Fixes #
Reference to #
/cc @li-ang 
```release-note
NONE
```

fix(render): avoid panic when root of tree carrier is nil

---

cmd/release-cli/create.go
cmd/release-cli/delete.go
cmd/release-cli/get.go
cmd/release-cli/list.go
cmd/release-cli/util.go

Fixes #
Reference to #
/cc @supereagle @caitong93 @zoumo @kdada @li-ang 
```release-note
NONE
```

feat: support kubeconfig-path for release-cli

---

Gopkg.lock
vendor/github.com/caicloud/clientset/util/status/pod.go

Fixes #
Reference to #
/cc @whalecold @li-ang 
```release-note
NONE
```

fix: choose the reason that shows more information

---

Makefile.expansion
pkg/controller/gc/controller.go

fix(gc): fix gc controller panic caused by concurruently reading map
Fixes #
Reference to #
/cc @zoumo 
```release-note
NONE
```

fix(gc): fix gc controller panic caused by concurruently reading map

---

Makefile

chore: update VERSION to v0.1.8
Fixes #
Reference to #
```release-note
NONE
```

chore: update VERSION to v0.1.8

---

Gopkg.lock
vendor/github.com/caicloud/clientset/pkg/apis/resource/v1beta1/storage.go
vendor/github.com/caicloud/clientset/util/event/event.go
vendor/github.com/caicloud/clientset/util/status/pod.go

chore(vendor): update vendor
Fixes #
Reference to #
/cc @hezhizhen @zxq-bit 
```release-note
NONE
```

chore(vendor): update vendor

---

pkg/controller/gc/controller.go

chore(log): add release collect log
Fixes #
Reference to #
```release-note
NONE
```

chore(log): add release collect log

---

pkg/release/apply.go
pkg/storage/release.go

delete suspend info when rollback version
Fixes #
Reference to #
/cc @zxq-bit @hezhizhen 
```release-note
NONE
```

[CPS-3127] fix(status): delete suspend info when rollback version

---

cmd/release-cli/lint.go
pkg/render/render.go

find by `go list ./... | grep -v /vendor | grep -v /test | xargs go test`
- 跑 go test 时发现的阻塞 test 的 warning
Fixes #
Reference to #
/cc @whalecold @hezhizhen 
```release-note
NONE
```

test(log): fix log print

---

Gopkg.lock
cmd/controller/app/controllers.go
cmd/controller/app/options/options.go
cmd/controller/app/release.go
pkg/controller/status/controller.go
vendor/github.com/caicloud/clientset/pkg/apis/loadbalance/v1alpha2/types.go
vendor/github.com/caicloud/clientset/util/status/pod_event.go

Fixes #
Reference to #
```release-note
NONE
```

[CPS-3018] fix(healthy): fix error phase of liveness failed

---

cmd/controller/app/controllers.go
cmd/controller/app/options/options.go
cmd/controller/app/release.go
pkg/controller/status/controller.go

chore(*): use time.Duraing instead of int32
Fixes #
Reference to #
/cc @hezhizhen @zxq-bit 
```release-note
NONE
```

chore(*): use time.Duraing instead of int32

---

pkg/controller/gc/controller.go

fix(log): optimize log
Fixes #
Reference to #
/cc @zxq-bit @hezhizhen 
```release-note
NONE
```

fix(log): optimize log

---

pkg/controller/gc/controller.go

Fixes #https://github.com/caicloud/prod-issue/issues/788
Reference to # https://github.com/caicloud/rudder/issues/125
```release-note
NONE
```

fix(gc): ignore the perfrom if release.status.manifest is mepty

---

pkg/controller/gc/controller.go
vendor/k8s.io/apimachinery/pkg/runtime/schema/group_version.go

refactor(*): add comments and tweak
Fixes #
Reference to #
/cc @whalecold @zxq-bit 
```release-note
NONE
```

refactor(*): add comments and tweak

---

.gitignore
.golangci.yml
Makefile
cmd/controller/app/controllers.go
cmd/controller/util.go
cmd/release-cli/get.go
cmd/release-cli/lint.go
cmd/release-cli/list.go
cmd/release-cli/main.go
cmd/release-cli/util.go
pkg/controller/gc/controller.go
pkg/controller/release/controller.go
pkg/controller/status/controller.go
pkg/controller/status/event.go
pkg/kube/client.go
pkg/kube/import_known_versions.go
pkg/kube/resource.go
pkg/kube/rest.go
pkg/kube/specified_ip.go
pkg/kube/specified_ip_util.go
pkg/release/apply.go
pkg/release/handler.go
pkg/release/release.go
pkg/render/render.go
pkg/render/tree.go
pkg/storage/release.go
pkg/store/store.go

fix(*): reformat code for lint
Fixes #
Reference to #
/cc @hezhizhen @zxq-bit 
```release-note
NONE
```

fix(*): reformat code for lint

---

Gopkg.lock
vendor/github.com/caicloud/rudder-client/status/apps/v1/daemonset.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/deployment.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/longrunning.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/register.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/statefulset.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/types.go
vendor/github.com/caicloud/rudder-client/status/apps/v1/universal.go
vendor/github.com/caicloud/rudder-client/status/batch/v1/job.go
vendor/github.com/caicloud/rudder-client/status/batch/v1/register.go
vendor/github.com/caicloud/rudder-client/status/batch/v1beta1/cronjob.go
vendor/github.com/caicloud/rudder-client/status/batch/v1beta1/register.go
vendor/github.com/caicloud/rudder-client/status/core/v1/configmap.go
vendor/github.com/caicloud/rudder-client/status/core/v1/pvc.go
vendor/github.com/caicloud/rudder-client/status/core/v1/register.go
vendor/github.com/caicloud/rudder-client/status/core/v1/secret.go
vendor/github.com/caicloud/rudder-client/status/core/v1/service.go
vendor/github.com/caicloud/rudder-client/status/umpire.go
vendor/github.com/caicloud/rudder-client/status/universal/types.go

chore(vendor): update rudder-client
Fixes #
Reference to #
/cc @whalecold @zxq-bit 
```release-note
NONE
```

chore(vendor): update rudder-client

---

README.md
pkg/kube/specified_ip.go

chore(README): add version table
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```

chore(README): add version table

---

Gopkg.lock
Gopkg.toml
cmd/controller/app/release.go
vendor/github.com/caicloud/go-common/kubernetes/client/README.md
vendor/github.com/caicloud/go-common/kubernetes/client/client.go
vendor/github.com/caicloud/go-common/kubernetes/client/doc.go

Fixes #
Reference to #
```release-note
NONE
```

feat(qps): support set qps and burst from command option

---

Makefile

Fixes #
Reference to #
```release-note
NONE
```

chore: change base image

---

OWNERS

Fixes #
Reference to #
/cc @whalecold @hezhizhen 
```release-note
NONE
```

chore(owner): clean owner

---

.gitignore
Makefile
build/controller/Dockerfile
build/controller/Dockerfile.arm64

Fixes #
Reference to http://jira.caicloud.xyz/browse/CPS-5949
/cc @whalecold @hezhizhen @bbbmj @liwandaniel 
```release-note
NONE
```

[CPS-5956] feat(*): support arm64v8

---

README.md

Fixes #
Reference to #
/cc @whalecold @qianlei90 
```release-note
NONE
```

fix(*): update readme

---

Gopkg.lock
cmd/controller/app/options/options.go
cmd/controller/app/release.go
vendor/github.com/caicloud/go-common/kubernetes/leaderelection/README.md
vendor/github.com/caicloud/go-common/kubernetes/leaderelection/doc.go
vendor/github.com/caicloud/go-common/kubernetes/leaderelection/healthz.go
vendor/github.com/caicloud/go-common/kubernetes/leaderelection/leaderelection.go
vendor/github.com/caicloud/go-common/signal/README.md
vendor/github.com/caicloud/go-common/signal/doc.go
vendor/github.com/caicloud/go-common/signal/stopsignal.go
vendor/k8s.io/apiserver/pkg/server/healthz/doc.go
vendor/k8s.io/apiserver/pkg/server/healthz/healthz.go
vendor/k8s.io/client-go/tools/leaderelection/OWNERS
vendor/k8s.io/client-go/tools/leaderelection/healthzadaptor.go
vendor/k8s.io/client-go/tools/leaderelection/leaderelection.go
vendor/k8s.io/client-go/tools/leaderelection/metrics.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/configmaplock.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/endpointslock.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/interface.go
vendor/k8s.io/client-go/tools/leaderelection/resourcelock/leaselock.go
vendor/k8s.io/klog/OWNERS
vendor/k8s.io/klog/README.md
vendor/k8s.io/klog/SECURITY_CONTACTS
vendor/k8s.io/klog/klog.go
vendor/k8s.io/klog/klog_file.go

Fixes #
Reference to #
```release-note
NONE
```

feat(healthz): add liveness

---

cmd/controller/app/controllers.go
pkg/controller/release/controller.go
pkg/release/handler.go

Fixes #
Reference to #
```release-note
NONE
```

[CPS-6393]fix(resync): resync the release controller when occured unknown error

---

cmd/controller/app/release.go

Fixes #
Reference to #
```release-note
NONE
```

[CPS-6947] fix(healthz): use raw http server for healthy check

---

Makefile
hack/read_cpus_available.sh

Fixes #
Reference to #
```release-note
NONE
```

[CPS-6742] chore(*): sync from golang-template-project

---

pkg/release/apply.go

Fixes #
Reference to #
/cc @qianlei90
```release-note
NONE
```

[CPS-7395]fix(update): post update release

---

cmd/controller/app/controllers.go
pkg/controller/release/controller.go
pkg/release/handler.go

* [CPS-6393]fix(resync): resync the release controller when occured unknown error
* use time.During instead of int32
backport  https://github.com/caicloud/rudder/pull/152
Fixes #
Reference to # 
/cc @qianlei90
```release-note
NONE
```

[CPS-6393] fix(resync): resync the release controller when occured unknown error (#152)

---

cmd/controller/app/controllers.go
cmd/controller/app/options/options.go
cmd/controller/app/release.go
pkg/controller/gc/controller.go
pkg/controller/gc/controller_test.go

Fixes #
Reference to #
```release-note
NONE
```

fix(limit): limit release history number

---

cmd/controller/app/controllers.go
cmd/controller/app/options/options.go
cmd/controller/app/release.go
pkg/controller/gc/controller.go
pkg/controller/gc/controller_test.go

* fix(limit): limit release history number
* fix
* change variable name
* add a test case
* add two test cases
* fix lint
* tweak comments
* tweak code
* tweak comments
Fixes #
Reference to #
/cc @hezhizhen
```release-note
NONE
```

[release-0.4]fix(limit): limit release history number (#159)

---

cmd/controller/app/controllers.go
cmd/controller/app/options/options.go
cmd/controller/app/release.go
pkg/controller/gc/controller.go
pkg/controller/gc/controller_test.go

* fix(limit): limit release history number
* fix
* change variable name
* add a test case
* add two test cases
* fix lint
* tweak comments
* tweak code
* tweak comments
Fixes #
Reference to #
/cc @hezhizhen
```release-note
NONE
```

[release-0.3]fix(limit): limit release history number (#159)

---

pkg/controller/gc/controller.go

Fixes #
Reference to #
```release-note
NONE
```

fix(lifecycle): remain resource for a short time to avoid mistake deleting

---

pkg/kube/apply/service.go
pkg/kube/apply/service_test.go

因为 kong ingress 需要将 annotations 配置到 service 上保证生效。更新 service 时不删除 service 上的 annotations，对 current service 和 desired service 的 annotations 做合并更新到新 service。
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```

feat: merge annotations of service updating

---

Makefile

不再构建 release-cli 
Fixes #
Reference to #
/cc @whalecold 
```release-note
NONE
```

chore(Makefile): remove build target release-cli

---

README.md

Fixes #
Reference to #
/cc @hezhizhen @whalecold 
```release-note
NONE
```

doc(README): fix version table

---

OWNERS

Fixes #
Reference to #
/cc @hezhizhen @yelongyu 
```release-note
NONE
```

chore(OWNERS): add owners

---

Makefile

Fixes #
Reference to #
/cc @hezhizhen 
```release-note
NONE
```

[CPS-8645] chore(Makefile): change to security golang version

---

pkg/controller/gc/controller.go

Co-authored-by: Lisheng Zheng <zhenglisheng@caicloud.io>
Fixes #
Reference to #
```release-note
NONE
```

[CPS-8684] fix(lifecycle): remain resource for a short time to avoid mistake deleting (#162)
